apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: code-learning
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: saileshdwivedy/frontend:latest
        imagePullPolicy: Always  # Ensures Kubernetes always pulls the latest image
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: http://backend-service:3000  # FIXED backend service URL

        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: code-learning
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
